package com.alad1nks.jaiqal.presentation
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import com.alad1nks.jaiqal.core.designsystem.*
import jaiqal.app.shared.generated.resources.*
import org.jetbrains.compose.resources.stringResource

@Composable fun AuthScreen(signUp:Boolean,onSubmit:(String,String)->Unit,onSwitch:()->Unit){var email by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var visible by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(Spacing.lg),verticalArrangement=Arrangement.Center){Text(stringResource(if(signUp)Res.string.sign_up else Res.string.sign_in),style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(Spacing.md));OutlinedTextField(email,{email=it},label={Text(stringResource(Res.string.email))},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(password,{password=it},label={Text(stringResource(Res.string.password))},singleLine=true,visualTransformation=if(visible) androidx.compose.ui.text.input.VisualTransformation.None else androidx.compose.ui.text.input.PasswordVisualTransformation(),trailingIcon={TextButton({visible=!visible}){Text(if(visible)"−" else "+")}},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(Spacing.md));PrimaryButton(stringResource(if(signUp)Res.string.sign_up else Res.string.sign_in),email.contains('@')&&password.length>=8){onSubmit(email,password)};TextButton(onClick=onSwitch){Text(stringResource(if(signUp)Res.string.sign_in else Res.string.sign_up))}}}
@Composable fun PlantsScreen(onAdd:()->Unit,onPlant:(String)->Unit){Scaffold(topBar={TopAppBar(title={Text(stringResource(Res.string.app_name))})},floatingActionButton={FloatingActionButton(onAdd){Text("+")}}){padding->LazyColumn(Modifier.padding(padding).padding(Spacing.md),verticalArrangement=Arrangement.spacedBy(Spacing.sm)){item{EmptyState(stringResource(Res.string.empty_plants),stringResource(Res.string.add_plant),onAdd)}}}}
@Composable fun PlantDetailsScreen(plantId:String,onCalibrate:()->Unit){LazyColumn(Modifier.fillMaxSize().padding(Spacing.md),verticalArrangement=Arrangement.spacedBy(Spacing.md)){item{Text(plantId,style=MaterialTheme.typography.headlineMedium)};item{Row(horizontalArrangement=Arrangement.spacedBy(Spacing.sm)){MetricCard(stringResource(Res.string.soil),"—",Modifier.weight(1f));MetricCard(stringResource(Res.string.temperature),"— °C",Modifier.weight(1f))}};item{Row(horizontalArrangement=Arrangement.spacedBy(Spacing.sm)){MetricCard(stringResource(Res.string.humidity),"— %",Modifier.weight(1f));MetricCard(stringResource(Res.string.light),"—",Modifier.weight(1f))}};item{Text(stringResource(Res.string.history),style=MaterialTheme.typography.titleLarge);EmptyState("No measurements")};item{PrimaryButton(stringResource(Res.string.calibrate),onClick=onCalibrate)}}}
@Composable fun FormScreen(title:String,onSave:()->Unit){var value by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(Spacing.lg),verticalArrangement=Arrangement.spacedBy(Spacing.md)){Text(title,style=MaterialTheme.typography.headlineMedium);OutlinedTextField(value,{value=it},modifier=Modifier.fillMaxWidth());PrimaryButton(stringResource(Res.string.save),value.isNotBlank(),onSave)}}
@Composable fun SimpleScreen(title:String,body:String=""){Column(Modifier.fillMaxSize().padding(Spacing.lg),verticalArrangement=Arrangement.spacedBy(Spacing.md)){Text(title,style=MaterialTheme.typography.headlineMedium);if(body.isNotEmpty())Text(body)}}
